lib/intercom/lib/typed_json_deserializer.rb, spec/unit/intercom/notification_spec.rb
Fixes https://github.com/intercom/intercom-ruby/issues/139
=> deal with nils in collection lists

README.md, lib/intercom.rb, lib/intercom/client.rb, lib/intercom/count.rb, lib/intercom/service/count.rb, spec/spec_helper.rb, spec/unit/intercom/count_spec.rb
=> counts api

README.md
Shouldn't use each do {|convo| ... } syntax as it's wrong.
(thanks to @TalkativeTree, this is just a rebase)
=> Fix the blocks in the Conversation documentation

lib/intercom/request.rb
This [python-intercom issue](https://github.com/jkeyes/python-intercom/issues/97) identifies two error codes that were not handled directly in python-intercom or intercom-ruby.
I didn't see any tests for the error codes, that's why there are none added to this PR. Hope this helps.
=> Adding support for parameter_not_found and unique_user_constraint error codes.

README.md, lib/intercom/client.rb, spec/unit/intercom/client_spec.rb
With some internal refactoring to use the Basic auth lingo instead of `app_id` and `api_key`
=> Support token keyword for oauth clients

README.md
=> Mark classes as code in README

lib/intercom/request.rb
Seems the Ruby JSON parser does not like the default encoding from GzipReader - it returns "Encoding::InvalidByteSequenceError: "\xC3" on US-ASCII".
=> Force unzipped body to UTF-8 encoding

README.md
The base class for all intercom errors is `Intercom::IntercomError`, not
`Intercom::Error`, as the README previously stated.
=> Fix name of base Intercom error class in README

lib/intercom/client_collection_proxy.rb, spec/spec_helper.rb, spec/unit/intercom/client_collection_proxy_spec.rb
This is related to https://github.com/intercom/intercom-ruby/issues/215
Previously we were returning all of the elements in a request even if the user specified a single page of results. Just adding in a check here to monitor the current page and return that page if that is what the user specified. This will allow users to specific the per page request number and the specific page they want returned.
=> Allow pagination for Ruby SDK

lib/intercom/service/count.rb, spec/spec_helper.rb, spec/unit/intercom/count_spec.rb
When trying to get the global conversation count `https://api.intercom.io/counts?type=conversation` you want to use the interface `intercom.counts.for_type(type: 'conversation')`
However, this currently doesn't work because the gem passes the empty `count=` param to the API which results in a server error: `Intercom::BadRequestError: for a conversation type, the count parameter must be admin`.
I changed the code so it won't send the count param to the server when it's nil.
=> Get global conversation count

README.md
Right now if you submit a bulk request, but do so incorrectly, you wont find out for awhile due to bulk processing times. By showing an example of how to properly nest companies, I think we can prevent possible mistakes from being made and also prevent CS from being confused.
=> Add example for bulk request

lib/intercom/errors.rb, lib/intercom/request.rb
Add a couple fields that come in handy when things go wrong.
* `request_id` that helps when contacting intercom support
* `field` that denotes the cause of a validation error
=> Add extra context to IntercomError

README.md
Minor stylistic, syntactic, and punctuation fixes.
- Remove / Add periods on sentences to match the sentences around them
- Change quotations to be consistent in a single line
- One code example with an unneeded `=` sign
- Move example parameters each to their own line
=> Readme style & typo fixes

lib/intercom/api_operations/find_all.rb, lib/intercom/service/base_service.rb, lib/intercom/service/event.rb, spec/spec_helper.rb, spec/unit/intercom/event_spec.rb
While examining [a PR for python-intercom](https://github.com/jkeyes/python-intercom/pull/141/) I noticed that intercom-ruby doesn't support multi-page results for `Event.find_all.
The API paging support for Events differs to that for the other resources, which means `paging_info_present` will always return `false` as there is no `type` attribute.
I'm unfamiliar with Ruby, so I hope this PR will prove useful.
=> Adding support for multi-page results for Event.find_all.

lib/intercom/client.rb, lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
It looks like the `RateLimitExceeded` exception was not being considered, this PR includes it.
=> raise a RateLimitExceeded error when the response code is 429

lib/intercom/traits/api_resource.rb, spec/unit/intercom/traits/api_resource_spec.rb
Adding `.to_s` properly follows the convention of not initializing `custom_attributes`
or any other attribute which passes the reserve field `type`. Not having `.to_s`, meant
if ApiResource is initialized by `User` or any other class, with a `Hash`, and
the attribute contains the reserved `type` `Hash` attribute, it would incorrectly
try to initialize the same property.
Ex of how it would fail, if `User` class is initialized with custom_attributes that
contains `type`:
```ruby
Intercom::User.new(email: "john@doe.com", custom_attributes: {"type"=>"ping"})
=> Intercom::AttributeNotSetError: 'each' called on Intercom::Ping but it has
not been set an attribute or does not exist as a method
...
```
A workaround would be that all keys were passed as strings, however this PR attempts
at …
=> Standardize comparison of attribute as string when input is Hash or JSON

.travis.yml, Gemfile, README.md, lib/intercom/client.rb, lib/intercom/request.rb, spec/spec_helper.rb, spec/unit/intercom/request_spec.rb
Resolving conflicts for PR #264 and adding unit tests.
Also updating some other tests due to warnings
=> Handle rate limits

README.md
For some reason it jumped to 3.5.19 as opposed to 3.5.18
Not sure why but updating readme to reflect this
=> Changing version, for some reason it skipped 18

lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
Closes #339 
Sometimes, parsing the decoded body will result in a `nil` value (i.e. if the `decoded_body` is `"null"`. Here, we only call `[]` if the `parsed_body` is something that can respond to it. 
Rather than raising a `NoMethodError`, the `parse_body` method will return `nil` if the `decoded_body` parses to `nil`.
=> add nil check for parsed_body

lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
Fixes #358 
CC: @choran - it seems that using the lonely operator (`&` ) breaks that method for anyone below Ruby 2.3 - sorry about that. 
Also, it seems that prior to 2.3, `JSON.parse` raises an error when passed a `null` value, rather than just returning `nil`. To be consistent across Ruby versions, seems like it makes more sense to raise an application error if the `decoded_body` is `'null'`, no matter what
Let me know if this seems more sensible!
=> Bugfix parse body

lib/intercom/errors.rb, lib/intercom/request.rb
Unintentionally merged directly to master, so reverting my changes.
=> Revert previous changes after unintentendly merging to master

README.md, changes.txt, lib/intercom/errors.rb, lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
When we get an error with code :conflict and error_code: "resource_conflict" we want to throw ResourceNotUniqueError.
=> added new error for specific error code

README.md
Fix an old link which no longer refers to the correct location
=> Update link to access tokens

spec/spec_helper.rb, spec/unit/intercom/client_collection_proxy_spec.rb
Currently, the spec has warnings about unused variables.
The warnings are displayed by warning option of Ruby.
```
$ RUBYOPT='-w' bundle exec rake
/home/pocke/ghq/github.com/intercom/intercom-ruby/spec/unit/intercom/client_collection_proxy_spec.rb:41: warning: assigned but unused variable - per_page
/home/pocke/ghq/github.com/intercom/intercom-ruby/spec/unit/intercom/client_collection_proxy_spec.rb:41: warning: assigned but unused variable - page
/home/pocke/ghq/github.com/intercom/intercom-ruby/spec/unit/intercom/client_collection_proxy_spec.rb:41: warning: assigned but unused variable - total_pages
/home/pocke/ghq/github.com/intercom/intercom-ruby/spec/unit/intercom/client_collection_proxy_spec.rb:41: warning: assigned but unused variable - total_count …
```
=> Suppress unused variable warnings in the spec

spec/unit/intercom/user_spec.rb
Because it is deprecated.
```
$ bundle exec rake
...
DEPRECATED: Use assert_nil if expecting nil from /home/pocke/ghq/github.com/intercom/intercom-ruby/spec/unit/intercom/user_spec.rb:242. This will fail in Minitest 6.
...
```
=> Use `assert_nil` instead of `must_equal nil`

Gemfile
Because this gem no longer supports Ruby 1.8.
https://github.com/intercom/intercom-ruby/blob/0fda77324201e5090fcbfbccb0a2744d96c73397/intercom.gemspec#L29
=> Remove gem dependency for Ruby 1.8

lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
For https://github.com/intercom/intercom-ruby/issues/385 
In cases where there is some sort of delay on the ruby server it's possible that the app's rate limit has already been reset. The call should process without breaking.
=> handle negative sleep time for rate limit retries

lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
See https://github.com/intercom/intercom-ruby/issues/398
=> #398. Fix X-RateLimit-Reset parsing.

Gemfile, intercom.gemspec
We should stop pulling in the JSON gem from Rubygems and instead use the version that ships with the language runtime.
Many gems including Rails did this: https://github.com/rails/rails/pull/23453
> All modern Rubies ship JSON as part of stdlib. Using the gem actually hurts multi-platform support due to build difficulties on Windows.
=> Remove json dependency

README.md
It isn't clear on how to convert leads into users.
This makes it clearer on what response objects that are returned with the `find` call, and also makes it clearer on how to best find the Intercom contact before converting it into a user.
See https://github.com/intercom/intercom-ruby/issues/419 for more information on why this is necessary.
This should only be a temporary change until we can change the SDK to only return one object using find, instead of a contact list.
=> Updating readme to make it clearer how to convert a lead into a user

README.md
It isn't clear right now how to find_all a contact's conversations, as demonstrated in this issue https://github.com/intercom/intercom-ruby/issues/422
This adds more concreted examples to the README on how to find contacts conversations.
=> Adding clearer instructions for find_all with contacts

README.md
The docs contain an incorrect call for tagging companies. The hash key should be `company_id`, not `id`. Passing `id` as a key throws an error.
Changed the hash key.
=> Use correct hash key in tagging docs

README.md, lib/intercom/service/conversation.rb, spec/spec_helper.rb, spec/unit/intercom/conversation_spec.rb
Closes https://github.com/intercom/intercom-ruby/issues/407
Adds an `all` method to the `conversations` module.
=> Allow all conversations to be listed

README.md, changes.txt, lib/intercom/version.rb, spec/unit/intercom/conversation_spec.rb
Made requested changes to:
https://github.com/intercom/intercom-ruby/pull/406
Also one of the requests they have in there shouldn't work. Admin_id should be supplied to reply to a user's last conversation
=> Residently conversations last reply

README.md, changes.txt, lib/intercom/version.rb
The last bump to 3.7.0 didn't seem to take effect correctly as evidenced from https://github.com/intercom/intercom-ruby/issues/445.
Bumping again to release properlye
=> Bump to 3.7.1

lib/intercom/errors.rb, lib/intercom/request.rb
Right now we handle CDA limit exceptions as an unknown error. It isn't an unknown error, we know exactly what's gone wrong - so we should handle it as such.
We now raise this on failure
```ruby
[7] Intercom(GEM)> client.users.save(user)
Intercom::CDALimitReachedError: Custom data limit reached
```
=> Add CDA Limit Reached Error handling

lib/intercom/errors.rb, lib/intercom/request.rb
We currently raise UnexpectedError when an admin isn't found. That isn't the case, we should raise a more informative error here.
=> Raise admin not found error

lib/intercom/client.rb, lib/intercom/errors.rb, lib/intercom/request.rb, spec/unit/intercom/client_spec.rb, spec/unit/intercom/request_spec.rb
With the release of API v1.1, it's now possible to [specify the version to use via a request header.
](https://developers.intercom.com/building-apps/v1.0/docs/api-versioning#section-selecting-the-version-via-the-api-request)
Currently, it's not possible to do this with the Ruby client. This makes it difficult to migrate to new versions of the API, as the only other way to change versions is via the Developer Hub. Since this setting applies globally (for all endpoints), it doesn't work well when selectively upgrading endpoints. Having finer-grained control over which versions are used for which requests is especially useful when accounting for breaking changes (of which v1.1 has a couple):
This PR adds an `api_version` kwarg that can be passed to `Intercom::Client`. This argument defaults …
=> Add API version support 

lib/intercom/errors.rb, lib/intercom/request.rb
We know when the error we receive is a `scroll_exists` error, we should be surfacing this inside the SDK.
=> Added error handling for scroll existing already

lib/intercom/errors.rb, lib/intercom/request.rb
We should be catching and handling this error more gracefully.
=> Add invalid document error handling

README.md
Update the readme to state that an event can also be created using a `user_id` as an identifier. Without it, it is not very clear on how to create an event when there is multiple users with the same email.
This is also helpful when there are multiple environments are using the same intercom account for testing purposes.
=> create an event using a user_id instead of email

intercom.gemspec
The gemspec was using deprecated methods.
The RubyGems gemspec property `rubyforge_project` has been removed without a replacement.
[Source code location with the deprecation](https://github.com/rubygems/rubygems/blob/a7e2f87e94791206d2e7bb12ff7ce75442811ce8/lib/rubygems/specification.rb#L735)
Drop the property. No replacement.
=> Gemspec: drop EOL'd property rubyforge_project

lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
To raise a more informative exception when a company is not found.
I added the `company_not_found` error code to the same case as the `not_found` code.
(Also removed an unused variable from request spec)
=> Raise ResourceNotFound when company is not found (fixes #484)

README.md
Code block is missing from here - https://github.com/intercom/intercom-ruby#customers
=> Add code block + docs link to README file

README.md, intercom.gemspec, lib/intercom/errors.rb, lib/intercom/request.rb, lib/intercom/version.rb, spec/spec_helper.rb, spec/unit/intercom/client_spec.rb, spec/unit/intercom/request_spec.rb
Addresses https://github.com/intercom/intercom-ruby/issues/491
=> [bugfix] handle unexpected response bodies

.circleci/config.yml
This adds a nice guarantee that methods used will be reliable for any
version of Ruby gem users may reasonably be using.
Example of the checks settings UI:
=> [chore] test against each major supported Ruby version

README.md, changes.txt, lib/intercom/version.rb
Bumping version up
Bumping to 3.9.2 because the version was changed in a previous PR, so the automatic bump tool immediately skipped 3.9.1
Yanking 3.9.2 could cause issues down the line, so simply skipping is fine.
=> Jonny/bump to 3.9.2

lib/intercom/request.rb, spec/unit/intercom/client_spec.rb
Closes https://github.com/intercom/intercom-ruby/issues/498
`rate_limit_details` was privatised, but is actually used outside of the request class. This wasn't covered in tests because we never directly made a call to the request class from outside of it.
This adds a test to make sure we're using that class in the client moving forward, and makes the `attr_accessor` not private.
=> Fix private method error and add test

lib/intercom/errors.rb, lib/intercom/request.rb, spec/unit/intercom/request_spec.rb
Addresses https://github.com/intercom/intercom-ruby/issues/502
Default handling for unexpected response bodies ([here](https://github.com/intercom/intercom-ruby/pull/492))
has revealed an unhandled 504 response from intercom.
Example message from UnexpectedResponseError:
```
Intercom::UnexpectedResponseError, Expected a JSON response body.
Instead got '<html> <head><title>504 Gateway Time-out</title></head>
<body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center>
</body> </html> ' with status code '504'.
```
=> [feature] handle 504 response

README.md, changes.txt, lib/intercom/version.rb
Bumping after https://github.com/intercom/intercom-ruby/pull/503
=>  Bump intercom to 3.9.4 

lib/intercom/client.rb, spec/unit/intercom/client_spec.rb
When trying to use the `Unstable` version, it fails validation, even though it is a valid API version. [See docs](https://developers.intercom.com/building-apps/docs/api-changelog).
```
ArgumentError: Malformed version number string Unstable
```
Accept `Unstable` as a valid API version.
=> Accept 'Unstable' API Version

README.md, changes.txt, lib/intercom/version.rb
=> Bump version to support the unstable API version

lib/intercom/api_operations/save.rb, spec/unit/intercom/contact_spec.rb
Missing client in the response of the object created.
Then you can not use the nested resources.
```ruby
contact = INTERCOM_CLIENT.contacts.new(email: "user@example.com")
INTERCOM_CLIENT.contacts.save(contact)
company = INTERCOM_CLIENT.contacts.new(company_id: "abc-company-example")
contact.add_company(id: company.id) # this fails!!
```
---
Before my fix, the specs that I created were broken:
```
be m spec/unit/intercom/contact_spec.rb 
Mocha deprecation warning at /github/intercom-ruby/spec/spec_helper.rb:5:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
Run options: -n "/^(test_0013_allows\\ setting\\ dates\\ to\\ nil\\ without\\ converting\\ them\\ to\\ 0|test_0015_will\\ allow\\ extra\\ attributes\\ in\\ response\\ from\\ …
```
=> [bugfix] Missing client in the response of the object created

README.md, lib/intercom/conversation.rb, spec/unit/intercom/conversation_spec.rb
Implemented `add_contact` and `remove_contact` actions in `Conversation`.
```ruby
conversation.add_contact(admin_id: admin.id, customer: { intercom_user_id: contact.id })
conversation.remove_tag(id: contact.id, admin_id: admin.id)
```
Fixes https://github.com/intercom/intercom-ruby/issues/515
=> [feature] Conversation : Add/remove nested resource 'contact'

changes.txt, lib/intercom/version.rb
New release for https://github.com/intercom/intercom-ruby/pull/516 & https://github.com/intercom/intercom-ruby/pull/517
=>  Bump intercom to 4.0.1

lib/intercom/traits/api_resource.rb, lib/intercom/traits/dirty_tracking.rb, spec/unit/intercom/traits/api_resource_spec.rb
SDK currently does not support,
- Dirty tracking nested objects.
- Serializing nested objects for sending requests
=> Added dirty_tracking support for nested objects

lib/intercom/traits/api_resource.rb, spec/unit/intercom/traits/api_resource_spec.rb
1. Current setup does not support checking if two resources are equal.
2. Current specs weren't tested with nested_fields which were typed.
https://github.com/intercom/intercom-ruby/blob/ba8e7b724e230d2cfd9ebc28e73a1de59e5f7551/spec/unit/intercom/traits/api_resource_spec.rb#L116
Above spec results in a failure as it tries to equate two resources.
- Implemented `.to_json`  at an `ApiResource` level
- Equated based on `.to_json` representation of a resource
=> Added support to check for equality of two resources

README.md, lib/intercom/version.rb
For bumping version to v4.1.0
These changes were missed.
`changes.txt` & `README.md` were updated earlier with new features.
=> Updates for version bump

lib/intercom/client.rb
This method allows us to use the deprecated `leads` endpoint in the SDK. It was omitted in error during the v4.0 release.
=> Add leads method to client

lib/intercom/request.rb
By allowing the raise_errors_on_failure to handle 4XX code errors, we are skipping our more verbose error handling done in raise_application_errors_on_failure.
=> refactor error handling

lib/intercom/service/conversation.rb, spec/unit/intercom/conversation_spec.rb
Related to https://github.com/intercom/intercom-ruby/pull/546
=> Add empty hash as payload for run assignment rules

lib/intercom/service/company.rb, spec/unit/intercom/company_spec.rb
Intercom has supported deleting companies since [API v2.0](https://developers.intercom.com/intercom-api-reference/v2.0/reference#delete-a-company). My app needs to be able to delete company information from Intercom and this would simplify my life! :pray: 
I leveraged the existing `delete` API operation and simply added it to the `company` service. Now you can call:
```ruby
client.companies.delete(company)
```
=> Allow companies to be deleted

lib/intercom/service/contact.rb, spec/unit/intercom/contact_spec.rb
Contacts in Intercom can be archived and unarchived, rather than being deleted outright. The gem doesn't have this ability yet.
I've added the methods to the service, following the same style as the api operations. I was considering creating a SoftArchive API operation to abstract the operation from the service, but it seems, contacts are the only entities, that have those endpoints.
=> Add ability to archive/unarchive contacts

lib/intercom/request.rb
Reverts intercom/intercom-ruby#548
Reverting as there might be a few error codes not handled, and this could result in a breaking change.
For example, The following error codes are used for with a http status code `404`,
`team_not_found`, `assignee_not_found`, `tag_not_found` & `conversation_part_or_message_not_found`
If we would've gone ahead with this change,
The existing `Intercom::ResourceNotFound` errors would switch to an `Intercom::UnexpectedError`.
This could break existing integrations that are possibly dependent on it.
There might be more error codes that would end up with the same behaviour for `404`, `401` & `403`.
=> Revert "refactor error handling"

README.md, lib/intercom/contact.rb, lib/intercom/segment.rb, spec/unit/intercom/contact_spec.rb
Support for listing contact segments was added in `API v2.2` ([Docs](https://developers.intercom.com/intercom-api-reference/reference#list-attached-segments))
Adding segments as a nested resource for `Contact`
=> Add support for listing contact segments

lib/intercom/base_collection_proxy.rb, spec/unit/intercom/base_collection_proxy_spec.rb
While using this gem, my team noticed that when you assign a collection with pagination to a variable (like the result of calling the search endpoint or simply listing all records of a resource), the collection can be entirely iterated only once.
After the first iteration, you can only access the last page of the cursor.
Here's a simple use case in which you'll experience this problem:
```
leads          = @intercom.contacts.search(...) # Collection with enough results to have pagination
total_leads    = leads.count                    # First iteration to count the results
iterated_leads = 0
leads.each { |lead| iterated_leads += 1 }       # Only the last page of the pagination cursor is being iterated, resulting in iterated_leads != total_leads
```
Later, we realized this is happening …
=> Fix collection successive iterations when there are multiple pages

README.md
This error was missing from the list of errors in README
=> Add Intercom::GatewayTimeoutError to README

README.md
The [Create Conversation endpoint](https://developers.intercom.com/intercom-api-reference/reference/create-a-conversation) now expects lead and user in request payload. Previously this endpoint accepted values of contact and user.
Updating the readme file accordingly
=> Updating readme according to new version changes -2.6 version

README.md, lib/intercom/service/contact.rb, spec/unit/intercom/contact_spec.rb
The change is introduced to update the SDK to support the latest change of the delete contact API.
The change:
The [Delete Contact endpoint](https://developers.intercom.com/intercom-api-reference/v2.6/reference/delete-contact) now allows permanent deletion of archived contacts directly. Previously, when attempting to delete an archived contact via the API, the contact needed to be unarchived and then deleted. This is no longer necessary.
Closes https://github.com/intercom/intercom/issues/259039 
Added a new endpoint to delete an archived contact.
=> Adding SDK endpoint to delete an archived contact

lib/intercom/base_collection_proxy.rb, spec/unit/intercom/base_collection_proxy_spec.rb
Arbitrary `@query` params could be passed in to filter resources, e.g. via the `#find_all` method. These params were not being forwarded through to the underlying HTTP client by BaseCollectionProxy in the same way that they are in ClientCollectionProxy.
Fixes #602.
=> Fix query params not being used in Intercom::BaseCollectionProxy

intercom.gemspec, spec/spec_helper.rb
Context:
-Doing this because of PR https://github.com/intercom/intercom-ruby/pull/619
-Main issue https://github.com/intercom/intercom/issues/418231
This PR updates our testing dependencies to be compatible with Ruby 2.6:
1. Updated Mocha integration method (spec/spec_helper.rb)
- Changed from deprecated mocha/setup to explicit mocha/minitest
- This eliminates the deprecation warning and ensures proper framework detection
2. Upgraded Mocha version (intercom.gemspec)
- Updated from ~> 1.0 to ~> 2.0
- Mocha 2.x includes proper support for the MiniTest → Minitest transition
=> Fix deprecated mocha version
