- README.md
I had to dig through the source a little to find this, so I think this will help some people out.
> added Intercom::User#delete to readme

- lib/intercom/client_collection_proxy.rb
fixes https://github.com/intercom/intercom-ruby/issues/161
> fix circular dependency warning ruby 2.2

- README.md
fixes https://github.com/intercom/intercom-ruby/issues/181
> Document conversation assignments

- lib/intercom.rb
- lib/intercom/api_operations/bulk/load_error_feed.rb
- lib/intercom/api_operations/bulk/submit.rb
- lib/intercom/client.rb
- lib/intercom/job.rb
- lib/intercom/lib/dynamic_accessors_on_method_missing.rb
- lib/intercom/service/event.rb
- lib/intercom/service/job.rb
- lib/intercom/service/user.rb
- spec/unit/intercom/event_spec.rb
- spec/unit/intercom/job_spec.rb
- spec/unit/intercom/user_spec.rb
> Bulk API support

- lib/intercom/client.rb
- spec/unit/intercom/client_spec.rb
fixes https://github.com/intercom/intercom-ruby/issues/209
> nil check app_id and api_key

- README.md
Just removing Gitter reference from Repo
> Removing Gitter forum reference

- lib/intercom/api_operations/find.rb
Means you can pass extra params with "/foo/bar" type calls
> Pass extra params with #find

- lib/intercom/api_operations/scroll.rb
- lib/intercom/scroll_collection_proxy.rb
- lib/intercom/service/user.rb
- spec/spec_helper.rb
- spec/unit/intercom/scroll_collection_proxy_spec.rb
Scroll Functionality with next and scroll method to 1/ return all users with one call and 2/ return 100 users with each call
> Issue 274 - Add Scroll Functionality

- README.md
@Skaelv would you mid taking a quick look here? Do we need anything else to explain the use cases?
> Adding info to README on scroll and pagination for users

- README.md
- lib/intercom/traits/incrementable_attributes.rb
- spec/unit/intercom/user_spec.rb
Adding a `decrement` convenience method to mirror the `increment` method.
> Add decrement method to incrementable traits

- README.md
- lib/intercom/service/admin.rb
- spec/spec_helper.rb
- spec/unit/intercom/admin_spec.rb
```ruby
intercom.admins.find(:id => admin_id)
```
> Add support to find admin by id

- README.md
In the Bulk Operations section, the user_id was being treated like an int. I changed to string.
> Changed user_id to a string

- README.md
> Update examples in README.md with ruby hash symbols syntax

- README.md
Just change the README file so merging in
> Api key update

- changes.txt
- lib/intercom/client.rb
Ability to change the base_url for local testing
> Use base_url in initialize parameter

- lib/intercom/errors.rb
- lib/intercom/request.rb
fix https://github.com/intercom/intercom-ruby/issues/329
> raise unauthorizedError on invalid token

- lib/intercom/errors.rb
- lib/intercom/request.rb
fix https://github.com/intercom/intercom-ruby/issues/335
> better error message when tryign to restore a blocked user

- README.md
- changes.txt
- circle.yml
- lib/intercom/traits/api_resource.rb
- lib/intercom/version.rb
- spec/unit/intercom/traits/api_resource_spec.rb
Fix for https://github.com/intercom/intercom/issues/63846
> Return object type

- .circleci/config.yml
- circle.yml
Migrating repo to circle 2.0 for https://github.com/intercom/intercom/issues/95392
> Migrate to Circle2.0

- README.md
I have updated the example in the documentation to be less vague about how to convert a lead to be a user. I got the code for this from [this comment](https://github.com/intercom/intercom-ruby/issues/330#issuecomment-304650167).
> Update documentation for upgrading lead to be a user

- README.md
Why are you making this change?
Technical details on your change
> Updating version to 3.6.0

- README.md
- changes.txt
- lib/intercom/version.rb
Why are you making this change?
Technical details on your change
> Adding new version 3.6.1

- README.md
Need to clarify how to update contacts using create. You have to provide an id or user_id
> Updating readme in relation to #404

- README.md
- changes.txt
- lib/intercom/version.rb
> Version 3 7 0

- README.md
- changes.txt
- lib/intercom/version.rb
> Jonny/bump to 3.7.2

- README.md
Why are you making this change?
Technical details on your change
> Adding example to query multiple users

- README.md
- changes.txt
- lib/intercom/version.rb
For https://github.com/intercom/intercom-ruby/pull/457
> Jonny/bump intercom to 3.7.3

- README.md
- changes.txt
- lib/intercom/version.rb
> Bump intercom to 3.7.4

- README.md
- changes.txt
- lib/intercom/version.rb
> Jonny/bump intercom to 3.7.6

- README.md
> Fix developer hub link

- README.md
- changes.txt
- lib/intercom/version.rb
https://github.com/intercom/intercom-ruby/pull/477
> Bump Intercom to 3.7.7

- README.md
- lib/intercom.rb
- lib/intercom/api_operations/search.rb
- lib/intercom/client.rb
- lib/intercom/customer.rb
- lib/intercom/search_collection_proxy.rb
- lib/intercom/service/customer.rb
- spec/spec_helper.rb
- spec/unit/intercom/search_collection_proxy_spec.rb
https://developers.intercom.com/intercom-api-reference/v0/reference#customers
Add core search feature for customers, including sorting and pagination
> Add support for Customer Search API

- changes.txt
- lib/intercom/version.rb
Update SDK version changes
Technical details on your change
> Conorkeating/release v4.0.0

- README.md
- changes.txt
- Updating Readme with new endpoints
- Updating changes.txt with changes for new version
> Readme update for v4.1.0

- README.md
- changes.txt
- lib/intercom/version.rb
Reverts intercom/intercom-ruby#530 and `changes.txt`
Will create a follow up PR post merge, to maintain commit history.
> Revert "Updates for version bump"

- changes.txt
- lib/intercom/version.rb
> Bump version to 4.1.1

- README.md
It's not clear on our README that our ruby wrapper has a built in method to untag companies
Update a readme
> update readme to show untag company action

- lib/intercom/scroll_collection_proxy.rb
Fixes https://github.com/intercom/intercom-ruby/issues/553
- As pointed out in https://github.com/intercom/intercom-ruby/pull/554, switching to accessing records using the `top_level_entity_key`
> Fixed issue with scroll collection proxy

- README.md
- changes.txt
- lib/intercom/version.rb
> Bump version to 4.1.2

- changes.txt
- lib/intercom/version.rb
bumping version to catalog latest changes
> Bump intercom to 4.1.3

- README.md
- lib/intercom/contact.rb
- spec/unit/intercom/contact_spec.rb
Updating the readme and url for subscriptions.
Change the path for subscriptions and update the readme file.
> Updating the readme and url for subscriptions

- README.md
- lib/intercom/base_collection_proxy.rb
- lib/intercom/lib/typed_json_deserializer.rb
- lib/intercom/utils.rb
- spec/unit/intercom/event_spec.rb
To fix https://github.com/intercom/intercom-ruby/issues/563 
Related to https://github.com/intercom/intercom/issues/262958 
Handling the way the collection is deserialised in this case.
> To fix events summary endpoint response

- README.md
- lib/intercom/version.rb
We did some work to make the api support version 2.6
> Bump intercom to 4.2.0

- spec/unit/intercom/company_spec.rb
- spec/unit/intercom/conversation_spec.rb
part of https://github.com/intercom/intercom-ruby/issues/602
> Add spec for find all on conversations
